name: Playwright Tests

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: 파이썬 설치
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          # 1. Pip 패키지 캐싱 활성화
          cache: 'pip'

      # 2. 플레이라이트 브라우저 캐싱 설정
      - name: 플레이라이트 브라우저 캐시 확인
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('requirements.txt') }}

      - name: 필요한 도구 설치
        run: |
          pip install -r requirements.txt
          # 3. 만약 캐시가 없다면(hit이 아니면) 브라우저를 새로 설치해라!
          if [ "${{ steps.playwright-cache.outputs.cache-hit }}" != 'true' ]; then
            playwright install --with-deps
          fi

      - name: 테스트 실행 (Allure 데이터 생성)
        run: pytest -s --alluredir=allure-results
        continue-on-error: true

      - name: Allure 보고서 생성 및 업로드
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: 깃허브 페이지로 보고서 배포
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report